version: '2'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:1.15.8
    container_name: lemp-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./docker/php/
    container_name: lemp-php
    restart: always
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
  db:
    image: mariadb:10.3.12
    container_name: lemp-mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lempdb
      - MYSQL_USER=lemp
      - MYSQL_PASSWORD=lemppassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    container_name: lemp-phpmyadmin
    restart: always
    depends_on:
      - php
      - db
    ports:
      - "8000:80"